# Generated by Django 2.2 on 2020-02-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smash_app', '0002_auto_20200225_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='video',
            field=models.URLField(max_length=225),
        ),
    ]
