# Generated by Django 2.2 on 2020-02-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smash_app', '0003_auto_20200225_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='loser_char',
            field=models.ManyToManyField(related_name='losing', to='smash_app.Character'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner_char',
            field=models.ManyToManyField(related_name='winning', to='smash_app.Character'),
        ),
    ]
